name: newsapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  get_it: ^8.0.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  mobx: ^2.1.1
  provider: ^6.0.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^8.0.0


dev_dependencies:
  mockito: ^5.4.4
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.0.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
